### ISSUE TITLE
Upgrade to NServiceBus 8.0

### ISSUE THREAD

**Issue by kkloet1** [jbogard/NServiceBus.Extensions.IntegrationTesting#12]
Any plans for upgrading to support NServiceBus 8.0 with the new OpenTelemetry implemenation that is built into NServiceBus?

**Comment by jbogard** [comment]
It'll be some time before I get to it, as the implementation changed from `DiagnosticSource` to `ActivitySource` which is quite different in their APIs. And, I don't have any pressing need to have this working. If someone wants to take a stab at it, I'm fine.

**Comment by bbrandt** [comment]
@jbogard  Thanks for the excellent tool! 

Is there now a testing solution other than NServiceBus.Extensions.IntegrationTesting that you are using with Integration tests for NServiceBus 8?  Or are you saying that you have not yet had to upgrade from NServiceBus 7 to 8 yourself?

**Comment by jbogard** [comment]
Done, and thanks for the contribution! 3.0.0 targets NSB 8.
